[package]
name = "btc-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.0"
bitcoincore-rpc = "0.17.0"
hex = "0.4.3"
tokio = { version = "1", features = ["full"] }
log = "0.4.20"
log4rs = "1.2.0"
env_logger = "0.9.0"
serde_json = "1.0.97"
dotenv = "0.15.0"
serde = {version = "1.0.164", features = ["derive"] }
anyhow = "1.0.71"
mongodb = "2.5.0"
consulrs = "0.1.0"
futures-util = "0.3.28"
indicatif = "0.17.5"
rust_decimal = "1.33.1"
